api/urls.py
from django.urls import path,include
from rest_framework.authtoken.views import obtain_auth_token  # <-- Here
from .views import CreateUserView,UserCreateAPIView,CustomRegisterView,ListEventsView,ListNewsView,attend,getstats,ProjectView,LoginUserDetailView,CustomLoginView,VeryNewCustomRegisterView,activate,testReset,ListInterestGroupView
from allauth.account.views import confirm_email
from django.contrib import admin
from django.conf.urls import url
from django.views.generic import TemplateView

from rest_auth.registration.views import RegisterView, VerifyEmailView, ConfirmEmailView
from .views import something,getmembers
from django.contrib.auth.views import password_reset_confirm,password_reset_complete



urlpatterns = [
  path('attend/', attend), # FOR ATTENDANCE
  path('getstats/',getstats), # FOR GETTING STATS
  path('getProjects/',ProjectView.as_view()), # GET PROJECTS 
  path('events/', ListEventsView.as_view(), name='getevents'),  # <-- And here
  path('news/', ListNewsView.as_view(), name='getnews'),  # <-- And here
   path('interestgroup/', ListInterestGroupView.as_view(), name='getinterestgroup'),  # <-- And here
  path('rest-auth/', include('rest_auth.urls')), # ALL REST AUTH URLS
  path('getmembers/', getmembers), # FOR ATTENDANCE

  
  ]

cia/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,re_path, include
from django.conf.urls import url
from django.views.static import serve 


from allauth.account.views import confirm_email
from api.views import attend,something,getUser,activate,VeryNewCustomRegisterView,testReset,CustomLoginView,register,profile,VisioneerCreate,visioneerview,getjsonmodel,getjsonmodel2

from django.views.generic import TemplateView
from django.contrib.auth.views import password_reset_confirm,password_reset_complete

from api.views import HelloView,index,loginPage
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView, RedirectView
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 


urlpatterns = [

    path('getjsonmodel/',getjsonmodel,name="getjsonmodel"),
    path('getjsonmodel2/',getjsonmodel2,name="getjsonmodel2"),

    #FOR WEB
    path('admin/', admin.site.urls), # ADMIN url
    path('accounts/',include('django.contrib.auth.urls')), # TO GET ALL USER URLS
    url(r'^account_inactive/$',TemplateView.as_view(),name = 'account_inactive'), # no idea y but register needs this
    path('',TemplateView.as_view(template_name="mainsite.html"),name="index"),
    path('events/',TemplateView.as_view(template_name="events.html"),name="events"),
    path('interest-groups/',TemplateView.as_view(template_name="interest-groups.html"),name="interest-groups"),
    path('projects/',TemplateView.as_view(template_name="projects.html"),name="projects"),
    path('register/',register,name="register"),
    path('profile/',profile,name='profile'),
    path('visioneer/', visioneerview, name='visioneer'),

    path('hack/', TemplateView.as_view(template_name="hack.html"), name='hackathon'),
    path('raj/', TemplateView.as_view(template_name="raj.html"), name='raj'),
    
    
    re_path('api/(?P<version>(v1|v2))/', include('api.urls')),    

    #FOR MOBILE REST API's
    url(r'rest/register/$', VeryNewCustomRegisterView.as_view(), name='rest_register'),
    url(r'^rest/login/$', CustomLoginView.as_view(), name='main_login'),
    url(r'rest/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'), # POST RESET MAIL 
    url(r'rest/reset/confirm/done/$', password_reset_complete, name='password_reset_complete'),
    path('activate/<uid>/<token>/',something),     # ACTIVATEING ACCOUNT - LINK MAILED 

    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth import get_user_model
from django.conf import settings
from phone_field import PhoneField







from datetime import datetime  



class UserType(models.Model):
    ut_id = models.IntegerField(primary_key=True)
    ut_name= models.CharField(max_length=255, null=False, default='type')
    def __str__(self):
        return "{} - {}".format(self.ut_id, self.ut_name)

class UserTypeRegister(models.Model):
    ut_id = models.IntegerField(primary_key=True)
    ut_name= models.CharField(max_length=255, null=False, default='type')
    def __str__(self):
        return "{} - {}".format(self.ut_id, self.ut_name)


class Dept(models.Model):
    dept_id = models.IntegerField(primary_key=True)
    dept_name = models.CharField(max_length=30,null=False,blank=True,default='dept_name')
    def __str__(self):
        return "{} - {}".format(self.dept_id, self.dept_name)


class User(AbstractUser):
    #u_id= models.IntegerField(primary_key=True)
    id= models.AutoField(primary_key=True)
    usn = models.TextField(max_length=10, blank=True)
    #dept = models.ForeignKey(Dept,on_delete=models.CASCADE,null=True,blank=True)
    dept = models.IntegerField(default=1,blank=True,null=True)
    phone_number = PhoneNumberField(blank=True)
    #user_t = models.ForeignKey(UserType,on_delete=models.CASCADE,null=True,blank=True)
    ut_id = models.IntegerField(default=1,blank=True,null=True)
    #ut = models.IntegerField(blank=True,default=1)
    def __str__(self):
        return "{} - {} - {} - {} - {} - {} - {}".format(self.id, self.usn,self.username,self.dept,self.email,self.phone_number,self.ut_id)
 


class Events(models.Model):
    # song title - s
    #"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
    e_id = models.AutoField(primary_key=True)
    e_image = models.ImageField(upload_to = 'images/events/', default = 'events/no-img.jpg')
    e_state = models.BooleanField(default=True)
    e_title = models.CharField(max_length=255, null=False, default='title')
    e_date = models.DateField('Event Date', default=datetime.now, blank=True)
    e_start_time = models.TimeField(default='12:00:00')
    e_end_time = models.TimeField(default='12:00:00',null=True,blank=True)
    e_venue = models.CharField(max_length=120,null=False, default='Venue')
    #e_organizer = models.CharField(max_length=255, null=False,default='Organizer')
    e_organizer = models.ForeignKey(User, on_delete=models.CASCADE)
    e_description = models.TextField(blank=True)
    e_score = models.IntegerField()
    e_registration_link = models.CharField(max_length=255, null=True, blank=True)
    e_photos_link = models.CharField(max_length=255, null=True,blank=True)
    e_medium_link = models.CharField(max_length=255, null=True,blank=True)
    e_code = models.CharField(max_length=255, null=True,blank=True)
    
    # name of artist or group/band
    def __str__(self):
        return "{} - {}".format(self.e_id, self.e_title)

class AttendRegister(models.Model):
    arid = models.AutoField(primary_key=True)
    e_id = models.ForeignKey(Events, on_delete=models.CASCADE)
   # e_score = models.For
    u_id = models.ForeignKey(User,on_delete=models.CASCADE)
    a_datetime = models.DateTimeField(default=datetime.now(), blank=True)
    
    
    def __str__(self):
        return "{} - {}".format(self.arid, self.e_id)



class News(models.Model):
    # song title - s
    #"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
    n_id = models.IntegerField(primary_key=True)
    n_title = models.CharField(max_length=255, null=False, default='title')
    n_desc = models.CharField(max_length=500, null=False, default='title')
    n_author = models.ForeignKey(User,on_delete=models.CASCADE)
    n_datetime = models.DateTimeField(default=datetime.now(), blank=True)
    n_image = models.ImageField(upload_to = 'images/news/', default = 'news/no-img.jpg')
    n_link = models.CharField(max_length=255,null=False, blank=True)
    def __str__(self):
        return "{} - {}".format(self.n_id, self.n_title)
##########################################################################

class Project(models.Model):
    p_id = models.AutoField(primary_key=True)
    p_state = models.BooleanField(default=True)
    p_title = models.CharField(max_length=200, null=False, default='title')
    p_image = models.ImageField(upload_to = 'images/projects/', default = 'projects/no-img.jpg')
    u_id = models.ForeignKey(User,on_delete=models.CASCADE)
    p_datetime = models.DateTimeField(default=datetime.now(), blank=True)
    p_desc = models.CharField(max_length=500, null=False, default='description')
    p_medium_link = models.CharField(max_length=250, null=False, default='https://www.medium.com')
    p_github_link = models.CharField(max_length=250, null=False, default='https://www.github.com')
    p_apply_link = models.CharField(max_length=250, null=False, default='https://www.google.com')
    def __str__(self):
        return "{} - {}".format(self.p_id, self.p_title)

class EmailOrUsernameModelBackend(object):
    """
    This is a ModelBacked that allows authentication with either a username or an email address.

    """
    def authenticate(self, username=None, password=None):
        if '@' in username:
            kwargs = {'email': username}
        else:
            kwargs = {'username': username}
        try:
            user = get_user_model().objects.get(**kwargs)
            if user.check_password(password):
                return user
        except User.DoesNotExist:
            return None

    def get_user(self, username):
        try:
            return get_user_model().objects.get(pk=username)
        except get_user_model().DoesNotExist:
            return None


class Visioneer(models.Model):
    firstname = models.CharField('First Name',max_length=100, null=False)
    lastname = models.CharField('Last Name',max_length=100, null=False)
    visioneerEmailAddress = models.EmailField('username@visioneer.atria.edu',max_length=100, null=False,unique=True)
    password = models.CharField('Password',max_length=100, null=False)
    passwordhashfunction = models.CharField(max_length=100, null=False, default='MD%')
    orgunitpath = models.CharField(max_length=100, null=False, default='org')
    recoveryemail = models.EmailField('Recovery Email',max_length=100, null=False)
    recoveryphone = PhoneField('Phone Number',blank=True,)
    homeaddress = models.CharField('Primary Address',max_length=100, null=False)
    employeeid = models.CharField('USN',max_length=100, null=False)
    departement = models.CharField(max_length=100, null=False, default='title')
    

class InterestGroup(models.Model):
    id = models.AutoField(primary_key=True)
    g_name= models.CharField('Group Name',max_length=275, null=False)
    g_desc= models.CharField('Group Description',max_length=400, null=False)
    g_img = models.ImageField(upload_to = 'images/group/', default = 'group/no-img.jpg')
    g_head= models.ForeignKey(User,on_delete=models.CASCADE)
    g_tellink= models.CharField('Telegram Link',max_length=225, null=False)
    g_medium=   models.CharField('Medium Link',max_length=225, null=False)
    def __str__(self):
        return "{} - {}".format(self.id, self.g_name)
    


class InterestGroupMember(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,)
    ig_id = models.ForeignKey(InterestGroup,on_delete = models.CASCADE)

api/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User
from .models import User,Visioneer
class UserSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=100, help_text='Required')
    class Meta:
        model = User
        fields = '__all__'


class ResetCustomForm(forms.ModelForm):
    class Meta:
        fields  = '__all__'


class VisioneerForm(forms.ModelForm):
    class Meta:
        model=Visioneer
        fields = ['firstname','lastname','visioneerEmailAddress','password','recoveryemail','recoveryphone','homeaddress','employeeid']

class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)

    class Meta:
        model = User
        fields = {'username', 'email','password1', 'password2','usn','dept','ut_id','phone_number','is_active' }

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']

        if commit:
            user.save()

api/templates/home_before.html
{% extends "base.html" %}

{% block content %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>django-rest-auth demo</h1>
    <p>Welcome in django-rest-auth demo project!</p>
  </div>
{% endblock %}

api/templates/interest-groups.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
    
    <title>Interest Groups</title>
<style>
    * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Josefin Sans', sans-serif;
    color: #E2E2E2;
}


:root {
    --bg: #151519;
    --bg2: rgb(17, 18, 21);
    --txtclr1: #2DFFCE;
    --txtclr2: #A0FFE9;
}

body {
    background: var(--bg);
}

header {
    height: auto;
    width: 100%;
    background: var(--bg2);
    padding: 3rem;
}

.heading h1 {
    font-size: 3rem;
    margin-top: 10px;
    margin-bottom: 10px;
}

.heading h2 {
    color: var(--txtclr1);
}

.desc {
    width: 600px;
    font-size: 1.5rem;
    font-family: sans-serif;
    line-height: 2rem;
    letter-spacing: 1px;
}

.desc span {
    font-family: sans-serif;
    color: var(--txtclr2);

}

.igs {
    padding: 3rem;
}

.igs .group:first-child {
    margin-top: 0px;
}

.igs .group {
    margin-top: 2rem;
    margin-bottom: 2rem;
}

.group h2 {
    color: var(--txtclr2);
    font-size: 1.8rem;
    margin-bottom: 5px;
}

.group p {
    font-size: larger;
    font-family: sans-serif;
    margin-bottom: 5px;
}
.group>a{
    display: block;
    width: fit-content;
    text-decoration: none;
    color: black;
    font-weight: 800;
    font-family: sans-serif;
    padding: 10px;
    background: var(--txtclr1);
    margin-top: 10px;
    border-radius: 2px;
    box-shadow: 0px 0px 10px 5px rgba(0, 0, 0, 0.301);
}
</style>


    <script >
        (() => {

function updateUI(json) {
    console.log(json);
    let igs = document.querySelector('.igs');
    
    json.forEach(e => {
        let group=document.createElement('div');
        group.className='group';
        group.innerHTML = `<h2>${e.g_name}</h2>
            <p>${e.g_desc}</p>
            <a href="${e.g_medium}">Get started</a>`;
        igs.appendChild(group);
    });
}


var api = 'test.ciadev.ninja';

let url = 'http://' + api + '/api/v2/interestgroup/?format=json';
var xmlhttp = new XMLHttpRequest();

xmlhttp.onreadystatechange = function () {
    if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
        var myArr = JSON.parse(xmlhttp.responseText);
        updateUI(myArr);
    }
};
xmlhttp.open("GET", url, true);
xmlhttp.send();

})();
    </script>
</head>

<body>
    <header>
        <div class="heading">
            <h2>Communities in Atria</h2>
            <h1>Interest Groups</h1>
        </div>

        <p class="desc">
            <span>Collaborate</span> with
            Like Minded People <br>
            and <span>Solve</span> Problems,<br>
            <span>Build</span> and <span>Grow</span> your Skills
        </p>
    </header>

    <div class="igs">

        


    </div>
</body>

</html>

api/templates/oops.html
<html>
    <head>

    </head>
    <body>
        <h1>Something went wrong</h1>
        <a href="{% url 'index' %}"> continue to test.ciadev.ninja</a  >

    </body>
</html>

api/templates/password_reset.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Password reset</h3><hr/>
    {% include "fragments/password_reset_form.html" %}
  </div>
{% endblock %}

api/templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Password reset confirmation</h3><hr/>
    {% include "fragments/password_reset_confirm_form.html" %}
  </div>
{% endblock %}



{% block script %}
    <script type="text/javascript">
        var url_elements = window.location.pathname.split('/');
        if (url_elements.length == 6){
            var uid = url_elements[url_elements.length - 3];
            if (uid !== undefined){
                $('input[name=uid]').val(uid);
            }
            var token = url_elements[url_elements.length - 2];
            if (token !== undefined){
                $('input[name=token]').val(token);
            }
        }
    </script>
{% endblock %}

api/templates/raj.html
<html>
    <head>xasxasxs</head>

</html>

api/templates/signup copy.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Signup</h3><hr/>
    {% include "fragments/signup_form.html" %}
  </div>
{% endblock %}

api/templates/signup.html
<html>

<body>  <div class="row">
    <h3>Signup</h3><hr/>
    {% include "fragments/signup_form.html" %}
  </div>
</body>

  </html>

api/templates/visioneer.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>

  <!--====== Required meta tags ======-->
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!--====== Title ======-->
  <title>CIA</title>
  {% load static %}

  <!--====== Favicon Icon ======-->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" type="image/png">

  <!--====== Bootstrap css ======-->
  <!-- <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css'%}"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>



  <!--====== Line Icons css ======-->
  <link rel="stylesheet" href="{% static 'assets/css/LineIcons.css'%}">
  <!-- <link rel="stylesheet" href="https://cdn.lineicons.com/1.0.1/LineIcons.min.css"> -->
  <link href='https://cdn.lineicons.com/1.0.1/LineIcons.min.css' rel='stylesheet'>

  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/GrayGrids/LineIcons/LineIcons.css"> -->

  <!--====== Magnific Popup css ======-->
  <!-- <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css'%}">  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.css"
    integrity="sha256-RdH19s+RN0bEXdaXsajztxnALYs/Z43H/Cdm1U4ar24=" crossorigin="anonymous" />

  <!--====== Slick css ======-->
  <!-- <link rel="stylesheet" href="{% static 'assets/css/slick.css'%}"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css"
    integrity="sha256-3h45mwconzsKjTUULjY+EoEkoRhXcOIU4l5YAw2tSOU=" crossorigin="anonymous" />

  <!--====== Animate css ======-->
  <!-- <link rel="stylesheet" href="{% static 'assets/css/animate.css'%}">  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css"
    integrity="sha256-a2tobsqlbgLsWs7ZVUGgP5IvWZsx8bTNQpzsqCSm5mk=" crossorigin="anonymous" />

  <!--====== Default css ======-->
  <link rel="stylesheet" href="{% static 'assets/css/default.css'%}">

  <!--====== Style css ======-->
  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">


</head>

<body>

  {% load crispy_forms_tags %}


  <div class="container">
    <div class="py-5 text-center">
      {% load static %}
      <!--  <img class="d-block mx-auto mb-4" src="{% static 'assets/brand/bootstrap-solid.svg' %}" alt="" width="72"
      height="72"> -->
      <h2>Visioneer Mail - Registration Form</h2>
      <p class="lead">You're a form away from getting something wonderful!</p>
    </div>





    <div class="col-md-8order-md-1">

      <form method="post" action="{% url 'visioneer'%}" novalidate>
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-4 mb-3">
            {{ form.firstname|as_crispy_field }}
          </div>
          <div class="col-md-4 mb-3">
            {{ form.lastname|as_crispy_field }}
          </div>
          <div class="col-md-4 mb-3">
            {{ form.employeeid|as_crispy_field }}
          </div>

        </div>




        <div class="row">
          <div class="col-md-4   mb-3">
            <!-- <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupPrepend2">@</span>
            </div> -->
            {{ form.visioneerEmailAddress|as_crispy_field }}


          </div>



          <div class="col-md-5 mb-3">

            
            <div id="div_id_recoveryemail" class="form-group">

              <label for="id_recoveryemail" class=" requiredField">
                Recovery Email<span class="asteriskField">*</span>
              </label>








              <div class="">
                <input type="email" name="recoveryemail" maxlength="100" class="emailinput form-control" required
                  id="id_recoveryemail"  value="{{ user.email }}"disabled/>












              </div>


            </div>

        

          </div>

          <div class="col-md-3 mb-3">

            {{ form.recoveryphone|as_crispy_field }}

          </div>

        </div>

        <div class="mb-3">

          {{ form.homeaddress|as_crispy_field }}

        </div>

        <div class="col mb-3">

          {{ form.password|as_crispy_field }}
        </div>

        <button class="btn btn-primary" type="submit">Submit form</button>

      </form>

    </div>
    <div class="container">
      <h1>.</h1>

    </div>




  </div>




  <!--====== jquery js ======-->
  <!-- <script src="{%static 'assets/js/vendor/modernizr-3.6.0.min.js'%}"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"
    integrity="sha256-ffw+9zwShMev88XNrDgS0hLIuJkDfXhgyLogod77mn8=" crossorigin="anonymous"></script>
  <!-- <script src="{%static 'assets/js/vendor/jquery-1.12.4.min.js'%}"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

  <!--====== Bo{%static 'otstrap js ======-->
  <!--  <script src="{%static 'assets/js/bootstrap.min.js'%}"></script>
    <script src="{%static 'assets/js/popper.min.js'%}"></script> -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <!--====== Sl{%static 'ick js ======-->
  <!-- <script src="{%static 'assets/js/slick.min.js'%}"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>

  <!--====== Is{%static 'otope js ======-->
  <!-- <script src="{%static 'assets/js/isotope.pkgd.min.js'%}"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js"
    integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>

  <!--====== Im{%static 'ages Loaded js ======-->
  <!-- <script src="{%static 'assets/js/imagesloaded.pkgd.min.js'%}"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js"
    integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
  <!--====== Ma{%static 'gnific Popup js ======-->
  <script src="{%static 'assets/js/jquery.magnific-popup.min.js'%}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"
    integrity="sha256-P93G0oq6PBPWTP1IR8Mz/0jHHUpaWL0aBJTKauisG7Q=" crossorigin="anonymous"></script>
  <!--====== Sc{%static 'rolling js ======-->
  <!-- <script src="{%static 'assets/js/scrolling-nav.js'%}"></script>
    <script src="{%static 'assets/js/jquery.easing.min.js'%}"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-one-page-nav/3.0.0/jquery.nav.min.js"></script>

  <!--====== wo{%static 'w js ======-->
  <script src="{%static 'assets/js/wow.min.js'%}"></script>

  <!--====== Ma{%static 'in js ======-->
  <script src="{%static 'assets/js/main.js'%}"></script>

</body>

</html>